### ISSUE TITLE
Unable to get through node install (dependency issues)

### ISSUE THREAD

**Issue by rickmanelius** [cerc-io/laconic-console#12]
I've tried node 16 and 18. Neither let's me get through `npm install`

**Comment by dboreham** [comment]
I don't believe this project is buildable as-is.

**Comment by rickmanelius** [comment]
So 4 things to clarify this one.
* I was in the wrong directory (repo root vs https://github.com/cerc-io/laconic-console/tree/main/packages/console-server).
* I'm on macOS. Apparently Lance was able to get `console-app` running on Linux.
* On macOS, the `console-server` worked great. The `console-app` did not.
* All of this will be made moot when #3 happens and `console-server` is replaced by `laconicd`

To that end, I'm going to close this down because it'll resolve by the time #3 is done.
