### ISSUE TITLE
Update package.json with lirewine packages after they are published

### ISSUE THREAD

**Issue by nikugogoi** [cerc-io/laconic-console#16]
- Add published lirewine packages
  - [x] [lirewine/debug](https://github.com/lirewine/debug/actions/workflows/publish.yaml)
  - [x] [lirewine/gem-core](https://github.com/lirewine/gem/actions/workflows/publish.yaml)
- Remove yarn link instructions from readme

**Comment by lanceseidman** [comment]
lirewine is not available for access for some, is this something that can be localized or must be pulled from the other repo?

**Comment by dboreham** [comment]
The lirewine projects, and their published packages in cerc npm registry will be made public.
